name: Chaos C Extension Feature Tests

on: [push]

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo make requirements

    - name: Build (gcc)
      run: |
        make clean
        make
        sudo make install

    - name: Run the tests (gcc)
      run: |
        make test-extensions-linux-gcc

    - name: Build (clang)
      run: |
        make clean
        make clang
        sudo make install

    - name: Run the tests (clang)
      run: |
        make test-extensions-linux-clang

  macos:
    name: macos
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        mv /usr/local/bin/gcc-8 /usr/local/bin/gcc
        make requirements

    - name: Build (gcc)
      run: |
        source ~/.bash_profile
        make clean
        make
        make install

    - name: Run the tests (gcc)
      run: |
        make test-extensions-macos-gcc

    - name: Build (clang)
      run: |
        source ~/.bash_profile
        make clean
        make clang
        make install

    - name: Run the tests (clang)
      run: |
        make test-extensions-macos-clang
