name: Linter Checks

on: [push]

jobs:
  main:
    name: linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt-get -y install build-essential bison flex libreadline-dev

    - name: Lint with Cppcheck
      run: |
        sudo apt-get -y install cppcheck
        cppcheck --force .
