name: Memory Leak Checks

on: [push]

jobs:
  main:
    name: memcheck
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        target:
          - ubuntu
          - debian
          - centos
          - fedora
          - archlinux
          - alpine

        include:
          - target: ubuntu
            image: ubuntu:latest
          - target: debian
            image: debian:latest
          - target: centos
            image: centos:latest
          - target: fedora
            image: fedora:latest
          - target: archlinux
            image: archlinux:latest
          - target: alpine
            image: alpine:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies (debian/ubuntu)
      run: |
        apt update
        apt install -y make valgrind
        make requirements
      if: matrix.target == 'ubuntu' || matrix.target == 'debian'

    - name: Install dependencies (centos)
      run: |
        yum install -y which make valgrind
        make requirements
      if: matrix.target == 'centos'

    - name: Install dependencies (fedora)
      run: |
        dnf install -y which make valgrind
        make requirements
      if: matrix.target == 'fedora'

    - name: Install dependencies (archlinux)
      run: |
        pacman -Syu --noconfirm which make valgrind
        make requirements
      if: matrix.target == 'archlinux'

    - name: Install dependencies (alpine)
      run: |
        apk update
        apk add bash which make valgrind
        make requirements
      if: matrix.target == 'alpine'

    - name: Build (gcc)
      run: |
        make clean
        make
        make install

    - name: Run the memory leak checks (gcc)
      run: |
        make memcheck

    - name: Build (clang)
      run: |
        make clean
        make clang
        make install

    - name: Run the memory leak checks (clang)
      run: |
        make memcheck
