name: Memory Leak Checks

on: [push]

jobs:
  main:
    name: memcheck
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo make requirements

    - name: Build (gcc)
      run: |
        make clean
        make
        sudo make install

    - name: Run the memory leak checks (gcc)
      run: |
        make memcheck

    - name: Build (clang)
      run: |
        make clean
        make clang
        sudo make install

    - name: Run the memory leak checks (clang)
      run: |
        make memcheck
