name: Automated Tests

on: [push]

jobs:
  main:
    name: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo make requirements

    - name: Build (gcc)
      run: |
        make clean
        make
        sudo make install

    - name: Run the tests (gcc)
      run: |
        make test

    - name: Build (clang)
      run: |
        make clean
        make clang
        sudo make install

    - name: Run the tests (clang)
      run: |
        make test
