name: Automated Tests

on: [push]

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo make requirements

    - name: Build (gcc)
      run: |
        make clean
        make
        sudo make install

    - name: Run the tests (gcc)
      run: |
        make test

    - name: Build (clang)
      run: |
        make clean
        make clang
        sudo make install

    - name: Run the tests (clang)
      run: |
        make test

  debian:
    name: debian
    runs-on: ubuntu-latest
    container:
      image: debian:stable

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apt update
        apt install make
        make requirements

    - name: Build (gcc)
      run: |
        make clean
        make
        make install

    - name: Run the tests (gcc)
      run: |
        make test

    - name: Build (clang)
      run: |
        make clean
        make clang
        make install

    - name: Run the tests (clang)
      run: |
        make test

  centos:
    name: centos
    runs-on: ubuntu-latest
    container:
      image: centos:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        yum install -y which make
        make requirements

    - name: Build (gcc)
      run: |
        make clean
        make
        make install

    - name: Run the tests (gcc)
      run: |
        make test

    - name: Build (clang)
      run: |
        make clean
        make clang
        make install

    - name: Run the tests (clang)
      run: |
        make test

  fedora:
    name: fedora
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        dnf install -y which make
        make requirements

    - name: Build (gcc)
      run: |
        make clean
        make
        make install

    - name: Run the tests (gcc)
      run: |
        make test

    - name: Build (clang)
      run: |
        make clean
        make clang
        make install

    - name: Run the tests (clang)
      run: |
        make test

  archlinux:
    name: archlinux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm which make
        make requirements

    - name: Build (gcc)
      run: |
        make clean
        make
        make install

    - name: Run the tests (gcc)
      run: |
        make test

    - name: Build (clang)
      run: |
        make clean
        make clang
        make install

    - name: Run the tests (clang)
      run: |
        make test
