name: Automated Tests

on: [push]

jobs:
  main:
    name: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt-get -y install build-essential bison flex libreadline-dev

    - name: Build (gcc)
      run: |
        make clean
        make
        sudo make install

    - name: Run the tests (gcc)
      run: |
        tests/run.sh

    - name: Build (clang)
      run: |
        make clean
        make clang
        sudo make install

    - name: Run the tests (clang)
      run: |
        tests/run.sh
